import "components/tour/award/tour_award";
import "components/tour/booking_btn/tour_booking_btn";
import "components/tour/call_to_action/tour_call_to_action";
import "components/tour/carousel/tour_carousel";
import "components/tour/comment/tour_comment";
import "components/tour/comment_form/tour_comment_form";
import "components/tour/cover_picture/tour_cover_picture";
import "components/tour/datepicker/tour_datepicker";
import "components/tour/description/tour_description";
import "components/tour/index/tour_index";
import "components/tour/item_actions/tour_item_actions";
import "components/tour/need/tour_need";import "components/tour/section/tour_section";
import "components/tour/proposed_by/tour_proposed_by";
import "components/tour/section_side/tour_section_side";
import "components/tour/side/tour_side";
import "components/tour/title/tour_title";
import "components/tour/youtube/tour_youtube";
